### ISSUE TITLE
Error after adding plugin

### ISSUE THREAD

**Issue by icemagno** [metadata101/iso19115-3#26]
After install this plugin I started to receive the following error when start my server:

```
[INFO] >>> jetty-maven-plugin:9.3.9.v20160517:run (default-cli) > test-compile @ web-app >>>
Downloading: https://raw.githubusercontent.com/geonetwork/core-maven-repo/master/org/geonetwork-opensource/schemas/3.1.0-SNAPSHOT/maven-metadata.xml
Downloading: http://maven.geo-solutions.it/org/geonetwork-opensource/schemas/3.1.0-SNAPSHOT/maven-metadata.xml
Downloading: http://mvnrepository.com/artifact/org/geonetwork-opensource/schemas/3.1.0-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.maven.apache.org/maven2/org/geonetwork-opensource/schemas/3.1.0-SNAPSHOT/maven-metadata.xml
Downloading: http://maven.seasar.org/maven2/org/geonetwork-opensource/schemas/3.1.0-SNAPSHOT/maven-metadata.xml
Downloading: https://raw.githubusercontent.com/geonetwork/core-maven-repo/master/org/geonetwork-opensource/schemas/3.1.0-SNAPSHOT/schemas-3.1.0-SNAPSHOT.pom
Downloading: http://mvnrepository.com/artifact/org/geonetwork-opensource/schemas/3.1.0-SNAPSHOT/schemas-3.1.0-SNAPSHOT.pom
Downloading: http://maven.geo-solutions.it/org/geonetwork-opensource/schemas/3.1.0-SNAPSHOT/schemas-3.1.0-SNAPSHOT.pom
Downloading: http://repo.maven.apache.org/maven2/org/geonetwork-opensource/schemas/3.1.0-SNAPSHOT/schemas-3.1.0-SNAPSHOT.pom
Downloading: http://maven.seasar.org/maven2/org/geonetwork-opensource/schemas/3.1.0-SNAPSHOT/schemas-3.1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.771 s
[INFO] Finished at: 2017-01-20T00:08:13-02:00
[INFO] Final Memory: 26M/63M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project web-app: Could not resolve dependencies for project org.geonetwork-opensource:web-app:war:3.3.0-SNAPSHOT: Failed to collect dependencies at org.geonetwork-opensource:schema-iso19115-3:jar:3.3.0-SNAPSHOT: Failed to read artifact descriptor for org.geonetwork-opensource:schema-iso19115-3:jar:3.3.0-SNAPSHOT: Could not find artifact org.geonetwork-opensource:schemas:pom:3.1.0-SNAPSHOT in core-maven-repo (https://raw.githubusercontent.com/geonetwork/core-maven-repo/master) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
root@nominatim:/home/magno/geonetwork/web#

```
Stack trace

```
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.geonetwork-opensource:web-app:war:3.3.0-SNAPSHOT: Failed to collect dependencies at org.geonetwork-opensource:schema-iso19115-3:jar:3.3.0-SNAPSHOT
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:180)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
        ... 27 more
```

**Comment by icemagno** [comment]
I've installed using https://github.com/metadata101/iso19115-3

**Comment by icemagno** [comment]
This is my build result after install:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] GeoNetwork opensource .............................. SUCCESS [  1.079 s]
[INFO] common utils ....................................... SUCCESS [  7.425 s]
[INFO] Caching xslt module ................................ SUCCESS [  0.313 s]
[INFO] ArcSDE module (dummy-api) .......................... SUCCESS [  0.437 s]
[INFO] GeoNetwork domain .................................. SUCCESS [ 13.084 s]
[INFO] Oaipmh modules ..................................... SUCCESS [  0.567 s]
[INFO] GeoNetwork Events .................................. SUCCESS [  0.343 s]
[INFO] GeoNetwork schema plugins .......................... SUCCESS [  0.032 s]
[INFO] GeoNetwork schema plugins core ..................... SUCCESS [  0.424 s]
[INFO] GeoNetwork schema plugin for ISO19139/119 standards  SUCCESS [  0.454 s]
[INFO] GeoNetwork core .................................... SUCCESS [ 11.957 s]
[INFO] GeoNetwork schema plugin for Dublin Core records retrieved by CSW SUCCESS [  0.118 s]
[INFO] GeoNetwork schema plugin for Dublin Core standard .. SUCCESS [  0.261 s]
[INFO] GeoNetwork schema plugin for ISO19110 standard ..... SUCCESS [  0.176 s]
[INFO] GeoNetwork schema plugin for ISO19115-3 standard ... SUCCESS [  0.257 s]
[INFO] GeoNetwork CSW server .............................. SUCCESS [  1.504 s]
[INFO] GeoNetwork harvesters .............................. SUCCESS [  2.715 s]
[INFO] GeoNetwork health monitor .......................... SUCCESS [  0.880 s]
[INFO] GeoNetwork services ................................ SUCCESS [ 10.412 s]
[INFO] Geonetwork Web Resources 4 Java .................... SUCCESS [  9.603 s]
[INFO] GeoNetwork INSPIRE Atom ............................ SUCCESS [  2.237 s]
[INFO] Solr module ........................................ SUCCESS [  0.055 s]
[INFO] Solr core configuration ............................ SUCCESS [  0.228 s]
[INFO] Solr proxy ......................................... SUCCESS [  0.497 s]
[INFO] messaging .......................................... SUCCESS [  0.715 s]
[INFO] workers ............................................ SUCCESS [  0.024 s]
[INFO] WFS features harvester ............................. SUCCESS [  1.305 s]
[INFO] Tests for schema plugins ........................... SUCCESS [  0.665 s]
[INFO] GeoNetwork user interface module ................... SUCCESS [  8.754 s]
[INFO] JS API and Service documentation ................... SUCCESS [  7.154 s]
[INFO] GeoNetwork Web module .............................. SUCCESS [ 41.178 s]
[INFO] GeoNetwork E2E Javascript Tests .................... SUCCESS [  0.533 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:06 min
[INFO] Finished at: 2017-01-20T00:06:20-02:00
[INFO] Final Memory: 133M/318M
[INFO] ------------------------------------------------------------------------

```

**Comment by fxprunayre** [comment]
So you solved your issue ? can we close ?
